Month 7 / step 1
starikan123/react-burger pull request #1
Opened 2023-05-06 11:26 UTC by starikan123

a pull request to review my work by the reviewer

2023-05-06 12:26 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Использовали `useMemo`
- Использовали деструктуризацию пропсов
- Отличная работа с `propTypes`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Проект не собирается, т.к. не совпадает регистр букв в названии файла и при импорте

Проверьте, что в системе контроля версий правильный регистр и при необходимости измените https://noteskeeper.ru/heritage/672/

 <img width="991" alt="Снимок экрана 2023-05-06 в 15 18 14" src="https://user-images.githubusercontent.com/60173362/236623563-c7e98276-e2d4-46a0-9571-0e4c8c663b65.png">

- В углу страницы есть цифра - 1 в кружочке - там её быть не должно

<img width="876" alt="Снимок экрана 2023-05-06 в 15 25 57" src="https://user-images.githubusercontent.com/60173362/236623916-a6c436b4-eefc-4c12-8571-627107f94ac2.png">

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-06 12:26 UTC, andryxxa93 commented on src/js/components/ingredient/ingredient.jsx
> +const Ingredient = ({ ingredient }) => {
**Можно лучше**

используйте для компонентов обертку React.memo, которая позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

https://ru.reactjs.org/docs/react-api.html#reactmemo
https://habr.com/ru/company/plarium/blog/442116/

2023-05-06 14:19 UTC, starikan123 commented
Hi
i've made the changes that you have requested
Awaiting for youe feedback.

2023-05-07 07:04 UTC, andryxxa93 commented
**Необходимо исправить**
- Все ингредиенты должны отображаться сразу списком, а не раскиданы по табам.


Во всём остальном - всё отлично! Вы можете приступать к финальному этапу сдачи работы.

2023-05-07 12:20 UTC, merged